export { default as DesExpertise } from './desExpertise';
export { default as Lists } from './lists';
export { default as Education } from './education';
export { default as Profile } from './Profile';
export { default as Description } from './description';
export { default as Skill } from './Skill';
export { default as Header } from './header';
export { default as Portofolio } from './portofolio';
export { default as Referensi } from './referensi';
